### ISSUE TITLE
 ImportError: cannot import name parse_signature_blob

### ISSUE THREAD

**Issue by jalsco** [sserrano44/pybitgo#1]
Hello - and thank you for  your work to make this package ! 

It installed on my python 2.7.6 with no errors using:  python setup.py install
Then to test I tried command line:   bitgo  access_token

But it fails with errors as follows: 

Traceback (most recent call last):
  File "/usr/local/bin/bitgo", line 9, in <module>
    load_entry_point('bitgo==0.1.2', 'console_scripts', 'bitgo')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2682, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2355, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/**init**.py", line 2361, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "build/bdist.linux-x86_64/egg/bitgo/**init**.py", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/bitgo/bitgo.py", line 46, in <module>
ImportError: cannot import name parse_signature_blob

How can I fix this ??

**Comment by IAlwaysBeCoding** [comment]
I came upon this issue while playing with this library in november too. Anyways, I submitted a pull request that should fix that import error.Good luck, I got a lot of inspiration from this library too when I was coding [BitGoPY](https://github.com/IAlwaysBeCoding/BitGoPY).

**Comment by jalsco** [comment]
Thank you for your quick response. I am pretty new to this - I am just trying to confirm what i need to do...  so I  must nstall your package (bitgopy )  - on top of pybitgo package ?  is that right ?

**Comment by IAlwaysBeCoding** [comment]
No , not at all. My package is a work-in-progress bitgo client library that am working on. However, I was looking at this library and the previous one made in november to see how some stuff was done. For your needs, all you have to do  is apply what is on the pull request https://github.com/sserrano44/pybitgo/issues/2 manually which is just changing one line.

**Comment by jalsco** [comment]
aaah ok :)

**Comment by IAlwaysBeCoding** [comment]
No problem, also if you don't want to apply the fix yourself. You can use this other fork version of someone else that applied that fixed to their fork.It is the same library but with that import error fixed https://github.com/hitfin/pybitgo

**Comment by jalsco** [comment]
i changed that line (46) to:
 from pycoin.tx.script.check_signature import parse_signature_blob 
and re-ran the install and yes - it fixed the problem - Thank you ! :+1:  :)
